[[redirects]]
  from = "/api/*"
  to = "http://43.201.73.11:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"